/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import Daonotes.NotesDao;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javaBeansNotes.CuteNotes;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angelica
 */
public class MyCuteNotes extends javax.swing.JFrame {

    /**
     * Creates new form MyCuteNotes
     */
    public void Listar(){
        try {
            NotesDao dao = new NotesDao();
            List<CuteNotes> listaNotes = dao.listarNotes();
            
            DefaultTableModel modelo = (DefaultTableModel) tblInicio.getModel();
            modelo.setNumRows(0);
            
            for(CuteNotes c: listaNotes){
                modelo.addRow(new Object[]{
                c.getDia(),    
                c.getAssunto(),
                });
            }
        } catch (Exception e) {
        }
    }
    
    public void LimparCampos(){
        txtAssunto.setText("");
        txtNotas.setText("");
    }
    
       
    public MyCuteNotes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panRaiz = new javax.swing.JPanel();
        panInicio = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInicio = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnVisualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panNovo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAssunto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNotas = new javax.swing.JTextArea();
        btnSalvar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        panVisualizar = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtVerNota = new javax.swing.JTextArea();
        btnOk = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panRaiz.setMaximumSize(new java.awt.Dimension(400, 300));
        panRaiz.setMinimumSize(new java.awt.Dimension(400, 300));
        panRaiz.setLayout(new java.awt.CardLayout());

        panInicio.setBackground(new java.awt.Color(255, 204, 255));
        panInicio.setMaximumSize(new java.awt.Dimension(400, 300));
        panInicio.setMinimumSize(new java.awt.Dimension(400, 300));
        panInicio.setPreferredSize(new java.awt.Dimension(400, 300));
        panInicio.setLayout(null);

        tblInicio.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        tblInicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Assunto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblInicio.getTableHeader().setReorderingAllowed(false);
        tblInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInicioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInicio);
        if (tblInicio.getColumnModel().getColumnCount() > 0) {
            tblInicio.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        panInicio.add(jScrollPane1);
        jScrollPane1.setBounds(10, 53, 380, 152);

        btnNovo.setBackground(new java.awt.Color(255, 204, 255));
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_basket_8726.png"))); // NOI18N
        btnNovo.setBorder(null);
        btnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        panInicio.add(btnNovo);
        btnNovo.setBounds(56, 223, 60, 60);

        btnExcluir.setBackground(new java.awt.Color(255, 204, 255));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_delete_48082.png"))); // NOI18N
        btnExcluir.setBorder(null);
        btnExcluir.setBorderPainted(false);
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        panInicio.add(btnExcluir);
        btnExcluir.setBounds(288, 223, 49, 60);

        btnVisualizar.setBackground(new java.awt.Color(255, 204, 255));
        btnVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_resolutions-05_897243_1.png"))); // NOI18N
        btnVisualizar.setBorder(null);
        btnVisualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });
        panInicio.add(btnVisualizar);
        btnVisualizar.setBounds(166, 223, 57, 60);

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel3.setText("My Cute Notes");
        panInicio.add(jLabel3);
        jLabel3.setBounds(92, 11, 205, 36);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo-lacinhos_large.jpg"))); // NOI18N
        panInicio.add(jLabel4);
        jLabel4.setBounds(0, 0, 400, 300);

        panRaiz.add(panInicio, "panInicio");

        panNovo.setBackground(new java.awt.Color(255, 255, 204));
        panNovo.setMaximumSize(new java.awt.Dimension(400, 300));
        panNovo.setMinimumSize(new java.awt.Dimension(400, 300));
        panNovo.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel1.setText("Assunto:");
        panNovo.add(jLabel1);
        jLabel1.setBounds(18, 5, 77, 28);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel2.setText("Notas:");
        panNovo.add(jLabel2);
        jLabel2.setBounds(18, 73, 59, 28);

        txtAssunto.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        panNovo.add(txtAssunto);
        txtAssunto.setBounds(10, 32, 380, 30);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtNotas.setColumns(20);
        txtNotas.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        txtNotas.setLineWrap(true);
        txtNotas.setRows(5);
        txtNotas.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtNotas);

        panNovo.add(jScrollPane2);
        jScrollPane2.setBounds(10, 107, 380, 133);

        btnSalvar.setBackground(new java.awt.Color(204, 153, 255));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_floppy_285657_1.png"))); // NOI18N
        btnSalvar.setBorder(null);
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        panNovo.add(btnSalvar);
        btnSalvar.setBounds(169, 258, 42, 38);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1083.png"))); // NOI18N
        panNovo.add(jLabel5);
        jLabel5.setBounds(0, 0, 400, 300);

        panRaiz.add(panNovo, "panNovo");

        panVisualizar.setBackground(new java.awt.Color(204, 204, 255));
        panVisualizar.setMaximumSize(new java.awt.Dimension(400, 300));
        panVisualizar.setMinimumSize(new java.awt.Dimension(400, 300));
        panVisualizar.setLayout(null);

        txtTitulo.setEditable(false);
        txtTitulo.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        txtTitulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panVisualizar.add(txtTitulo);
        txtTitulo.setBounds(10, 20, 380, 34);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtVerNota.setEditable(false);
        txtVerNota.setColumns(20);
        txtVerNota.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        txtVerNota.setLineWrap(true);
        txtVerNota.setRows(5);
        txtVerNota.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtVerNota);

        panVisualizar.add(jScrollPane3);
        jScrollPane3.setBounds(10, 70, 380, 170);

        btnOk.setBackground(new java.awt.Color(255, 0, 255));
        btnOk.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        btnOk.setForeground(new java.awt.Color(255, 255, 255));
        btnOk.setText("Ok");
        btnOk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        panVisualizar.add(btnOk);
        btnOk.setBounds(153, 252, 94, 37);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/unicorn.png"))); // NOI18N
        panVisualizar.add(jLabel6);
        jLabel6.setBounds(0, 0, 400, 300);

        panRaiz.add(panVisualizar, "panVisualizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panRaiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panRaiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout) panRaiz.getLayout();
        c1.show(panRaiz, "panInicio");
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout) panRaiz.getLayout();
        c1.show(panRaiz, "panNovo");
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        try {
            CuteNotes obj = new CuteNotes();
            obj.setAssunto(txtAssunto.getText());
            obj.setNote(txtNotas.getText());
            
            NotesDao dao = new NotesDao();
            dao.CadastrarNotes(obj);
            JOptionPane.showMessageDialog(null, "Nota salva com sucesso!");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar: " + erro, "Erro", JOptionPane.WARNING_MESSAGE);
        }
        
        this.Listar();
        this.LimparCampos();
        
        CardLayout c1 = (CardLayout) panRaiz.getLayout();
        c1.show(panRaiz, "panInicio");
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Listar();
        
        //lblData.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date(System.currentTimeMillis())));
        
    }//GEN-LAST:event_formWindowActivated

    private void tblInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInicioMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            String assunto = tblInicio.getValueAt(tblInicio.getSelectedRow(),tblInicio.getSelectedColumn()).toString();
            try {
            NotesDao dao = new NotesDao();
            List<CuteNotes> listaNotes = dao.verNotes(assunto);
                for (CuteNotes c : listaNotes){

                    txtTitulo.setText(c.getAssunto());
                    txtVerNota.setText(c.getNote());
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Selecione um Assunto");
            }
            CardLayout c1 = (CardLayout) panRaiz.getLayout();
            c1.show(panRaiz, "panVisualizar");
        }
        
    }//GEN-LAST:event_tblInicioMouseClicked

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        // TODO add your handling code here:
        String assunto = tblInicio.getValueAt(tblInicio.getSelectedRow(),tblInicio.getSelectedColumn()).toString();
                
        try {
           NotesDao dao = new NotesDao();
           List<CuteNotes> listaNotes = dao.verNotes(assunto);
           for (CuteNotes c : listaNotes){
               
               txtTitulo.setText(c.getAssunto());
               txtVerNota.setText(c.getNote());
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecione um Assunto");
        }
        CardLayout c1 = (CardLayout) panRaiz.getLayout();
        c1.show(panRaiz, "panVisualizar");
        
        
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        try {
            CuteNotes obj = new CuteNotes();
            obj.setAssunto(tblInicio.getValueAt(tblInicio.getSelectedRow(),1).toString());
            
            NotesDao dao = new NotesDao();
            dao.excluirNotes(obj);
            
            DefaultTableModel modelo = (DefaultTableModel) tblInicio.getModel();
            modelo.removeRow(tblInicio.getSelectedRow());
            
            JOptionPane.showMessageDialog(null, "Nota excluída com sucesso!");
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir " + e);
        }
        
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyCuteNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyCuteNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyCuteNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyCuteNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyCuteNotes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panInicio;
    private javax.swing.JPanel panNovo;
    private javax.swing.JPanel panRaiz;
    private javax.swing.JPanel panVisualizar;
    private javax.swing.JTable tblInicio;
    private javax.swing.JTextField txtAssunto;
    private javax.swing.JTextArea txtNotas;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextArea txtVerNota;
    // End of variables declaration//GEN-END:variables
}
